
services:  # Определение сервисов
  redis:  # Настройки сервиса Redis
    image: redis:7.2.4-alpine  # Используемый образ

  django:  # Настройки сервиса Django
    container_name: django  # Имя контейнера
    build:
      context: .  # Путь в директорию, из которой Dockerfile будет собран для создания контейнера Django.
    ports:  # Применение порта 8000 из контейнера на хосте
      - 8000:8000
    volumes:
      - ./back:/app  # Монтирование локального каталога проекта в контейнер
    command: python manage.py runserver 0.0.0.0:8000  # Команда запуска сервера Django
    depends_on:
      - redis  # Зависимость от сервиса Redis
    env_file:
      - ./.env

  celery:  # Настройки сервиса Celery
    container_name: celery  # Имя контейнера
    build:
      context: .  # Путь к celery.py
    command: celery -A diplom_project worKer -l INFO  # Команда запуска Celery с логированием на уровне INFO
    volumes:
      - ./back:/app  # Монтирование локального каталога проекта в контейнер
    depends_on:
      - django  # Зависимость от сервиса Django
